version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 8
        commands:
            - npm install
    build:
        commands:
            - npm run build
    post_build:
        commands:
            - zip -r app-api.zip .
artifacts:
    files:
        - app-api.zip
