version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 8
        commands:
            - npm install
    build:
        runtime-versions:
            nodejs: 8
        commands:
            - npm run build
